version: 0.2

phases:
  pre_build:
    commands:
      # Install Hugo on Ubuntu
      - sudo apt update
      - sudo apt install hugo -y

  build:
    commands:
      # Translate and update the _index.md files in their respective locations

  post_build:
    commands:
      # Build the Hugo project
      - hugo

      # Get the S3 bucket name from environment variable
      - s3_bucket_name="workshop-1.5"

      # Empty the bucket before pushing the new content
      - aws s3 rm "s3://$s3_bucket_name/" --recursive

      # Upload everything (including content and public folders) to S3
      - aws s3 sync . "s3://$s3_bucket_name/"
